# Redis images Verison TEST 1.0

FROM ubuntu:14.04
MAINTAINER Galen turnbull "jxe20@qq.com"
ENV REFRESHED_AT 2015-04-14


RUN apt-get -y update 
RUN apt-get -y install cmatrix 
EXPOSE 80
EXPOSE 22

CMD []

